import { defineConfig } from 'vite'
import preact from '@preact/preset-vite'
import { VitePWA } from 'vite-plugin-pwa'
import type { Plugin } from 'vite'

/**
 * Vite plugin that injects Cross-Origin Isolation headers on every response.
 *
 * WHY: SharedArrayBuffer (used for zero-latency audio timing data shared
 * between the main thread, AudioWorklets, and Web Workers) is only available
 * in cross-origin-isolated contexts. The browser requires BOTH of these
 * headers to enable that context:
 *
 *   Cross-Origin-Opener-Policy: same-origin
 *   Cross-Origin-Embedder-Policy: require-corp
 *
 * Without them, `new SharedArrayBuffer(...)` throws at runtime.
 */
function crossOriginIsolation(): Plugin {
  return {
    name: 'cross-origin-isolation',
    configureServer(server) {
      server.middlewares.use((_req, res, next) => {
        res.setHeader('Cross-Origin-Opener-Policy', 'same-origin')
        res.setHeader('Cross-Origin-Embedder-Policy', 'require-corp')
        next()
      })
    },
    configurePreviewServer(server) {
      server.middlewares.use((_req, res, next) => {
        res.setHeader('Cross-Origin-Opener-Policy', 'same-origin')
        res.setHeader('Cross-Origin-Embedder-Policy', 'require-corp')
        next()
      })
    },
  }
}

/**
 * Exported so `src/__tests__/offline-shell.test.ts` can assert on it. These
 * are decisions with consequences a build error would not catch — a glob that
 * stops matching the worklet still builds, and still ships.
 */
export const PWA_OPTIONS: Parameters<typeof VitePWA>[0] = {
  strategies: 'injectManifest',
  srcDir: 'src',
  filename: 'sw.ts',
  /**
   * We register explicitly with `workbox-window` in main.tsx rather than
   * letting the plugin inject a snippet, so the registration is visible in
   * source and can decide for itself when an update may be applied.
   */
  injectRegister: null,
  /**
   * The installed app (8.4). `display: 'standalone'` is the field that matters
   * beyond appearance: Chrome grants an installed PWA autoplay, so the
   * engine-warmup screen skips its `awaiting-tap` step and opens straight on
   * `awaiting-kit`. That path already exists in `enterApp` — installing is
   * what triggers it, not new code.
   *
   * Icons are generated by `npm run generate:icons`; see pwa-assets.config.ts,
   * which also records that the source artwork is a placeholder.
   */
  /**
   * Public assets the manifest does not already name. The manifest's own icons
   * are injected by the plugin, so globbing `png` here as well would list them
   * twice — harmless while the revisions match, and a failed worker install
   * (`add-to-cache-list-conflicting-entries`) the day they do not. That would
   * take offline down entirely, so `check-precache.mjs` now fails on any
   * duplicate rather than trusting the two sources to agree.
   */
  includeAssets: ['favicon.ico', 'apple-touch-icon-180x180.png'],
  manifest: {
    name: 'InThePocket — drum practice',
    short_name: 'InThePocket',
    description:
      'Zero-latency practice drills for electronic drummers. Works offline, next to the kit.',
    start_url: '/',
    scope: '/',
    display: 'standalone',
    background_color: '#0a0c14',
    theme_color: '#0a0c14',
    icons: [
      { src: 'pwa-64x64.png', sizes: '64x64', type: 'image/png' },
      { src: 'pwa-192x192.png', sizes: '192x192', type: 'image/png' },
      { src: 'pwa-512x512.png', sizes: '512x512', type: 'image/png' },
      { src: 'maskable-icon-512x512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
    ],
  },
  injectManifest: {
    /**
     * `.woff` is deliberately absent. Fontsource emits both formats in one
     * `src:` list and every browser that has AudioWorklet and
     * SharedArrayBuffer takes the `.woff2`, so the `.woff` files are never
     * requested — precaching them would add 92KB of downloads that no drummer
     * will ever use.
     */
    globPatterns: ['**/*.{js,css,html,svg,woff2}'],
  },
  /**
   * Off in dev. Playwright runs `npm run dev`, and a service worker serving
   * yesterday's chunks to a suite that asserts on millisecond timing is a
   * source of failures nobody would attribute correctly.
   */
  devOptions: { enabled: false },
}

// https://vite.dev/config/
export default defineConfig({
  plugins: [
    preact(),
    crossOriginIsolation(),
    /**
     * Offline shell (8.3). `injectManifest`, not `generateSW`: the service
     * worker is ours (`src/sw.ts`) and the plugin only injects the precache
     * list into it. A generated worker would be a black box in the one part of
     * the app whose failure mode is indistinguishable from P-1.
     */
    VitePWA(PWA_OPTIONS),
  ],
})
